### ISSUE TITLE
Results not showing

### ISSUE THREAD

**Issue by CaptainRon76** [CaptainRon76/captainron76.github.io#6]

**Comment by denislemire** [comment]
Reviewing, commit 12a86e7ba4ca3117df34a4190af2cb07786086b3 removed the submit button per issue #3 but JavaScript code still existed to set its display property to none at the end of the trivia.

I've removed the problematic Javascript line in commit c2c4842428107c1ad3dcc0300a1ad9155d755869 and changed its color in commit feb522cd6de7ce10b4165e435aba12ae817a5b15
